#!/usr/bin/env python3
import json
import os
import re
import sys


def to_s_type(struct_name):
    overrides = {
        "VkPhysicalDeviceVulkan11Features": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES",
        "VkPhysicalDeviceVulkan12Features": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES",
        "VkPhysicalDeviceVulkan13Features": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES",
        "VkPhysicalDeviceVulkan11Properties": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES",
        "VkPhysicalDeviceVulkan12Properties": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES",
        "VkPhysicalDeviceVulkan13Properties": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES",
    }
    if struct_name in overrides:
        return overrides[struct_name]

    name = struct_name
    if name.startswith("Vk"):
        name = name[2:]
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).upper()
    s2 = s2.replace("ROBUSTNESS2", "ROBUSTNESS_2")
    return f"VK_STRUCTURE_TYPE_{s2}"


def flatten_properties(data, current_path=""):
    flat = []
    if isinstance(data, dict):
        for k, v in data.items():
            next_path = f"{current_path}.{k}" if current_path else k
            flat.extend(flatten_properties(v, next_path))
    elif isinstance(data, bool):
        flat.append((current_path, True, "1" if data else "0"))
    elif isinstance(data, int):
        flat.append((current_path, False, str(data)))
    elif isinstance(data, str):
        flat.append((current_path, False, data))
    elif isinstance(data, list):
        expr = " | ".join(str(item) for item in data)
        flat.append((current_path, False, expr if expr else "0"))
    return flat


def deep_merge_dicts(target, source):
    for k, v in source.items():
        if isinstance(v, dict) and k in target and isinstance(target[k], dict):
            deep_merge_dicts(target[k], v)
        else:
            target[k] = v


def generate_cpp_header(aggregated_data):
    out = []
    out.append("/* Generated by generate_spoofed_profile.py - DO NOT EDIT MANUALLY */")
    out.append("#pragma once")
    out.append("#include <vulkan/vulkan.h>")
    out.append("#include <cstddef>")
    out.append("")

    out.append("const SpoofedExtension SPOOFED_EXTENSIONS[] = {")
    for ext_name, spec_ver in sorted(aggregated_data["extensions"].items()):
        out.append(f'    {{ "{ext_name}", {spec_ver} }},')
    out.append("};")
    out.append(
        "const size_t SPOOFED_EXTENSIONS_COUNT = sizeof(SPOOFED_EXTENSIONS) / sizeof(SPOOFED_EXTENSIONS[0]);"
    )
    out.append("")

    core_features = aggregated_data["features"].get("VkPhysicalDeviceFeatures", {})
    out.append("const SpoofedFeature SPOOFED_CORE_FEATURES[] = {")
    for f_name in sorted(core_features.keys()):
        out.append(
            f'    {{ VK_STRUCTURE_TYPE_MAX_ENUM, offsetof(VkPhysicalDeviceFeatures, {f_name}), "VkPhysicalDeviceFeatures", "{f_name}" }},'
        )
    out.append("};")
    out.append(
        "const size_t SPOOFED_CORE_FEATURES_COUNT = sizeof(SPOOFED_CORE_FEATURES) / sizeof(SPOOFED_CORE_FEATURES[0]);"
    )
    out.append("")

    out.append("const SpoofedFeature SPOOFED_NEXT_FEATURES[] = {")
    for struct_name, struct_feats in sorted(aggregated_data["features"].items()):
        if struct_name == "VkPhysicalDeviceFeatures":
            continue
        s_type = to_s_type(struct_name)
        for f_name in sorted(struct_feats.keys()):
            out.append(
                f'    {{ {s_type}, offsetof({struct_name}, {f_name}), "{struct_name}", "{f_name}" }},'
            )
    out.append("};")
    out.append(
        "const size_t SPOOFED_NEXT_FEATURES_COUNT = sizeof(SPOOFED_NEXT_FEATURES) / sizeof(SPOOFED_NEXT_FEATURES[0]);"
    )
    out.append("")

    core_properties = aggregated_data["properties"].get(
        "VkPhysicalDeviceProperties", {}
    )
    flat_core_props = flatten_properties(core_properties)
    out.append("const SpoofedProperty SPOOFED_CORE_PROPERTIES[] = {")
    for path, is_bool, expr in sorted(flat_core_props):
        if is_bool and expr == "false":
            continue
        is_bool_str = "true" if is_bool else "false"
        out.append(
            f'    {{ VK_STRUCTURE_TYPE_MAX_ENUM, offsetof(VkPhysicalDeviceProperties, {path}), {is_bool_str}, {expr}, "VkPhysicalDeviceProperties", "{path}" }},'
        )
    out.append("};")
    out.append(
        "const size_t SPOOFED_CORE_PROPERTIES_COUNT = sizeof(SPOOFED_CORE_PROPERTIES) / sizeof(SPOOFED_CORE_PROPERTIES[0]);"
    )
    out.append("")

    out.append("const SpoofedProperty SPOOFED_PROPERTIES[] = {")
    for struct_name, struct_props in sorted(aggregated_data["properties"].items()):
        if struct_name == "VkPhysicalDeviceProperties":
            continue
        s_type = to_s_type(struct_name)
        flat_next_props = flatten_properties(struct_props)
        for path, is_bool, expr in sorted(flat_next_props):
            if is_bool and expr == "0":
                continue
            is_bool_str = "true" if is_bool else "false"
            out.append(
                f'    {{ {s_type}, offsetof({struct_name}, {path}), {is_bool_str}, {expr}, "{struct_name}", "{path}" }},'
            )
    out.append("};")
    out.append(
        "const size_t SPOOFED_PROPERTIES_COUNT = sizeof(SPOOFED_PROPERTIES) / sizeof(SPOOFED_PROPERTIES[0]);"
    )
    out.append("")

    return "\n".join(out)


def main():
    profile_path = "VP_D3D12_VKD3D_PROTON_profile.json"
    if not os.path.exists(profile_path):
        print(f"Error: Profile definition file '{profile_path}' not found.")
        sys.exit(1)

    with open(profile_path, "r") as f:
        data = json.load(f)

    target_profile = sys.argv[1] if len(sys.argv) > 1 else "VP_D3D12_FL_12_0_baseline"

    profiles = data.get("profiles", {})
    if target_profile not in profiles:
        print(
            f"Error: Target profile '{target_profile}' not found inside schema profiles block."
        )
        print(f"Available options: {list(profiles.keys())}")
        sys.exit(1)

    print(f"Aggregating properties for profile target: {target_profile}")
    active_capabilities = profiles[target_profile].get("capabilities", [])
    all_capabilities = data.get("capabilities", {})

    aggregated = {"extensions": {}, "features": {}, "properties": {}}

    for cap_name in active_capabilities:
        if cap_name not in all_capabilities:
            print(
                f"Warning: Capability reference block '{cap_name}' undefined in root dictionary."
            )
            continue

        cap_block = all_capabilities[cap_name]

        for ext, ver in cap_block.get("extensions", {}).items():
            aggregated["extensions"][ext] = max(
                aggregated["extensions"].get(ext, 0), ver
            )

        for struct_name, fields in cap_block.get("features", {}).items():
            if struct_name not in aggregated["features"]:
                aggregated["features"][struct_name] = {}
            for field_name, value in fields.items():
                if value:
                    aggregated["features"][struct_name][field_name] = True

        for struct_name, props in cap_block.get("properties", {}).items():
            if struct_name not in aggregated["properties"]:
                aggregated["properties"][struct_name] = {}
            deep_merge_dicts(aggregated["properties"][struct_name], props)

    header_content = generate_cpp_header(aggregated)
    os.makedirs("src", exist_ok=True)
    with open("src/generated_spoofed_profile.hpp", "w") as f:
        f.write(header_content)


if __name__ == "__main__":
    main()
